[package]
name = "seamstress"
version = "0.1.0"
authors = ["Mani Sundararajan"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0"
imageproc = "0"
